<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/10/16 16:40:14
sfConfig::add(array(
  'env_signin_sso_cookie_name' => 'diesel_sso',
  'env_satellites' => array (
  'pages' => 
  array (
    'type' => 'pages',
    'relative_path' => NULL,
    'assets_path' => '/assets/pages',
    'url' => 'http://www.diesel.h-art.it/',
    'searchcached' => true,
    'urlListOfItem' => 'http://www.diesel.h-art.it/itemsmap.xml',
    'urlDiscoverItem' => 'http://www.diesel.h-art.it/itemsmap.xml?url=%%__URL__%%',
  ),
  'be' => 
  array (
    'type' => 'be',
    'relative_path' => '/be',
    'assets_path' => '/assets/core',
    'url' => 'http://www.diesel.h-art.it/be/',
    'searchcached' => true,
    'urlListOfItem' => 'http://www.diesel.h-art.it/core/itemsmap.xml',
    'urlDiscoverItem' => 'http://www.diesel.h-art.it/core/itemsmap.xml?url=%%__URL__%%',
  ),
  'api' => 
  array (
    'type' => 'api',
    'relative_path' => '/api',
    'assets_path' => '/assets/core',
    'url' => 'http://core.diesel.h-art.it/api.php/',
    'searchcached' => false,
    'urlListOfItem' => 'http://www.diesel.h-art.it/api/itemsmap.xml',
    'urlDiscoverItem' => 'http://www.diesel.h-art.it/api/itemsmap.xml?url=%%__URL__%%',
  ),
  'core' => 
  array (
    'type' => 'core',
    'relative_path' => '/core',
    'assets_path' => '/assets/core',
    'url' => 'http://www.diesel.h-art.it/core/',
    'searchcached' => true,
    'urlListOfItem' => 'http://www.diesel.h-art.it/core/itemsmap.xml',
    'urlDiscoverItem' => 'http://www.diesel.h-art.it/core/itemsmap.xml?url=%%__URL__%%',
  ),
  'collection' => 
  array (
    'type' => 'collection',
    'relative_path' => '/collection',
    'assets_path' => '/assets/collection',
    'url' => 'http://www.diesel.h-art.it/collection/',
    'searchcached' => true,
    'urlListOfItem' => 'http://www.diesel.h-art.it/collection/itemsmap.xml',
    'urlDiscoverItem' => 'http://www.diesel.h-art.it/collection/itemsmap.xml?url=%%__URL__%%',
  ),
  'storelocator' => 
  array (
    'type' => 'storelocator',
    'relative_path' => '/store-locator',
    'assets_path' => '/assets/store-locator',
    'url' => 'http://www.diesel.h-art.it/store-locator/',
    'searchcached' => true,
    'urlListOfItem' => 'http://www.diesel.h-art.it/store-locator/itemsmap.xml',
    'urlDiscoverItem' => 'http://www.diesel.h-art.it/store-locator/itemsmap.xml?url=%%__URL__%%',
  ),
  'sneakers' => 
  array (
    'type' => 'sneakers',
    'relative_path' => '/sneakers',
    'assets_path' => '/assets/sneakers',
    'url' => 'http://www.diesel.h-art.it/sneakers/',
    'searchcached' => true,
    'urlListOfItem' => 'http://www.diesel.h-art.it/sneakers/itemsmap.php',
    'urlDiscoverItem' => 'http://www.diesel.h-art.it/sneakers/itemsmap.php?url=%%__URL__%%',
  ),
  'freshandbright' => 
  array (
    'type' => 'freshandbright',
    'relative_path' => '/freshandbright',
    'assets_path' => '/freshandbright',
    'url' => 'http://www.diesel.h-art.it/freshandbright/',
    'searchcached' => true,
    'urlListOfItem' => 'http://www.diesel.h-art.it/freshandbright/itemsmap.xml',
    'urlDiscoverItem' => 'http://www.diesel.h-art.it/freshandbright/itemsmap.xml?url=%%__URL__%%',
  ),
),
));
