generator:
  class: sfDoctrineGenerator
  param:
    model_class:           SlProductLine
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sl_product_line
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    ~
      edit:    
        display: [name, ord, visible]
      new:
        display: [name, ord, visible]
