<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/10/15 08:20:48

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=c8dieselcn',
  'username' => 'c8dieselcn',
  'password' => 'lUToBdklrr',
  'attributes' => 
  array (
    'default_table_collate' => 'utf8_unicode_ci',
    'default_table_charset' => 'utf8',
  ),
  'name' => 'doctrine',
)),);
