<?php
// auto-generated by sfViewConfigHandler
// date: 2013/11/11 09:45:21
$response = $this->context->getResponse();

if ($this->actionName.$this->viewName == 'facebookSplashSuccess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else if ($this->actionName.$this->viewName == 'facebookStoreSuccess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else if ($this->actionName.$this->viewName == 'facebookFinderSuccess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else if ($this->actionName.$this->viewName == 'printSuccess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}

if ($templateName.$this->viewName == 'facebookSplashSuccess')
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else
  {
    $this->setDecoratorTemplate('' == 'layoutFacebook' ? false : 'layoutFacebook'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html; charset=utf-8', false);
  $response->addMeta('title', 'Diesel - jeans, clothing, shoes, watches, apparel, underwear and sunglasses', false, false);
  $response->addMeta('description', 'Diesel&#039;s Fall Winter 2013 Main Collection and the Fall Winter Preview Collection.', false, false);
  $response->addMeta('language', 'en_EN', false, false);
  $response->addMeta('robots', 'NOODP', false, false);
  $response->addMeta('msnbot', 'NOODP', false, false);
  $response->addMeta('googlebot', 'NOODP', false, false);
  $response->addMeta('author', 'H-art: http://www.h-art.it/', false, false);
  $response->addMeta('msvalidate.01', '82A9598193937FC116E896B8B7179581', false, false);

  $response->addStylesheet('/assets/core/css/storelocator.css', '', array ());
  $response->addStylesheet('/assets/core/css/storelocator-new.css', '', array ());
  $response->addStylesheet('/assets/core/css/storelocator-restyling.css', '', array ());
  $response->addStylesheet('/assets/core/css/store-locator-facebook.css', '', array ());
  $response->addJavascript('http://maps.google.com/maps/api/js?sensor=true', '', array ());
}
else if ($templateName.$this->viewName == 'facebookStoreSuccess')
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else
  {
    $this->setDecoratorTemplate('' == 'layoutFacebook' ? false : 'layoutFacebook'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html; charset=utf-8', false);
  $response->addMeta('title', 'Diesel - jeans, clothing, shoes, watches, apparel, underwear and sunglasses', false, false);
  $response->addMeta('description', 'Diesel&#039;s Fall Winter 2013 Main Collection and the Fall Winter Preview Collection.', false, false);
  $response->addMeta('language', 'en_EN', false, false);
  $response->addMeta('robots', 'NOODP', false, false);
  $response->addMeta('msnbot', 'NOODP', false, false);
  $response->addMeta('googlebot', 'NOODP', false, false);
  $response->addMeta('author', 'H-art: http://www.h-art.it/', false, false);
  $response->addMeta('msvalidate.01', '82A9598193937FC116E896B8B7179581', false, false);

  $response->addStylesheet('/assets/core/css/storelocator.css', '', array ());
  $response->addStylesheet('/assets/core/css/storelocator-new.css', '', array ());
  $response->addStylesheet('/assets/core/css/storelocator-restyling.css', '', array ());
  $response->addStylesheet('/assets/core/css/store-locator-facebook.css', '', array ());
  $response->addJavascript('http://maps.google.com/maps/api/js?sensor=true', '', array ());
}
else if ($templateName.$this->viewName == 'facebookFinderSuccess')
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else
  {
    $this->setDecoratorTemplate('' == 'layoutFacebook' ? false : 'layoutFacebook'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html; charset=utf-8', false);
  $response->addMeta('title', 'Diesel - jeans, clothing, shoes, watches, apparel, underwear and sunglasses', false, false);
  $response->addMeta('description', 'Diesel&#039;s Fall Winter 2013 Main Collection and the Fall Winter Preview Collection.', false, false);
  $response->addMeta('language', 'en_EN', false, false);
  $response->addMeta('robots', 'NOODP', false, false);
  $response->addMeta('msnbot', 'NOODP', false, false);
  $response->addMeta('googlebot', 'NOODP', false, false);
  $response->addMeta('author', 'H-art: http://www.h-art.it/', false, false);
  $response->addMeta('msvalidate.01', '82A9598193937FC116E896B8B7179581', false, false);

  $response->addStylesheet('/assets/core/css/storelocator.css', '', array ());
  $response->addStylesheet('/assets/core/css/storelocator-new.css', '', array ());
  $response->addStylesheet('/assets/core/css/storelocator-restyling.css', '', array ());
  $response->addStylesheet('/assets/core/css/store-locator-facebook.css', '', array ());
  $response->addJavascript('http://maps.google.com/maps/api/js?sensor=true', '', array ());
}
else if ($templateName.$this->viewName == 'printSuccess')
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else
  {
    $this->setDecoratorTemplate('' == 'layoutPrint' ? false : 'layoutPrint'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html; charset=utf-8', false);
  $response->addMeta('title', 'Diesel - jeans, clothing, shoes, watches, apparel, underwear and sunglasses', false, false);
  $response->addMeta('description', 'Diesel&#039;s Fall Winter 2013 Main Collection and the Fall Winter Preview Collection.', false, false);
  $response->addMeta('language', 'en_EN', false, false);
  $response->addMeta('robots', 'NOODP', false, false);
  $response->addMeta('msnbot', 'NOODP', false, false);
  $response->addMeta('googlebot', 'NOODP', false, false);
  $response->addMeta('author', 'H-art: http://www.h-art.it/', false, false);
  $response->addMeta('msvalidate.01', '82A9598193937FC116E896B8B7179581', false, false);

  $response->addStylesheet('/assets/core/css/storelocator.css', '', array ());
  $response->addStylesheet('/assets/core/css/storelocator-new.css', '', array ());
  $response->addStylesheet('/assets/core/css/storelocator-restyling.css', '', array ());
  $response->addStylesheet('/assets/core/css/print.css', '', array ());
  $response->addJavascript('http://maps.google.com/maps/api/js?sensor=true', '', array ());
}
else
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html; charset=utf-8', false);
  $response->addMeta('title', 'Diesel - jeans, clothing, shoes, watches, apparel, underwear and sunglasses', false, false);
  $response->addMeta('description', 'Diesel&#039;s Fall Winter 2013 Main Collection and the Fall Winter Preview Collection.', false, false);
  $response->addMeta('language', 'en_EN', false, false);
  $response->addMeta('robots', 'NOODP', false, false);
  $response->addMeta('msnbot', 'NOODP', false, false);
  $response->addMeta('googlebot', 'NOODP', false, false);
  $response->addMeta('author', 'H-art: http://www.h-art.it/', false, false);
  $response->addMeta('msvalidate.01', '82A9598193937FC116E896B8B7179581', false, false);

  $response->addStylesheet('http://localhost/die_sel/css/common.css', '', array ());
  $response->addStylesheet('/assets/core/css/storelocator.css', '', array ());
  $response->addStylesheet('/assets/core/css/storelocator-new.css', '', array ());
  $response->addStylesheet('/assets/core/css/storelocator-restyling.css', '', array ());
  $response->addJavascript('http://maps.google.com/maps/api/js?sensor=true', '', array ());
}

