<?php

/**
 * BaseSlCountry
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $iso
 * @property integer $world_area_id
 * @property integer $user_id
 * @property SlWorldArea $SlWorldArea
 * @property sfGuardUser $sfGuardUser
 * @property Doctrine_Collection $SlStore
 * @property Doctrine_Collection $SlCity
 * 
 * @method string              getName()          Returns the current record's "name" value
 * @method string              getIso()           Returns the current record's "iso" value
 * @method integer             getWorldAreaId()   Returns the current record's "world_area_id" value
 * @method integer             getUserId()        Returns the current record's "user_id" value
 * @method SlWorldArea         getSlWorldArea()   Returns the current record's "SlWorldArea" value
 * @method sfGuardUser         getSfGuardUser()   Returns the current record's "sfGuardUser" value
 * @method Doctrine_Collection getSlStore()       Returns the current record's "SlStore" collection
 * @method Doctrine_Collection getSlCity()        Returns the current record's "SlCity" collection
 * @method SlCountry           setName()          Sets the current record's "name" value
 * @method SlCountry           setIso()           Sets the current record's "iso" value
 * @method SlCountry           setWorldAreaId()   Sets the current record's "world_area_id" value
 * @method SlCountry           setUserId()        Sets the current record's "user_id" value
 * @method SlCountry           setSlWorldArea()   Sets the current record's "SlWorldArea" value
 * @method SlCountry           setSfGuardUser()   Sets the current record's "sfGuardUser" value
 * @method SlCountry           setSlStore()       Sets the current record's "SlStore" collection
 * @method SlCountry           setSlCity()        Sets the current record's "SlCity" collection
 * 
 * @package    collections
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSlCountry extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sl_country');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('iso', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('world_area_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SlWorldArea', array(
             'local' => 'world_area_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasMany('SlStore', array(
             'local' => 'id',
             'foreign' => 'country_id'));

        $this->hasMany('SlCity', array(
             'local' => 'id',
             'foreign' => 'country_id'));
    }
}