<?php

/**
 * BaseStoreType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $type
 * @property Doctrine_Collection $Store
 * 
 * @method string              getType()  Returns the current record's "type" value
 * @method Doctrine_Collection getStore() Returns the current record's "Store" collection
 * @method StoreType           setType()  Sets the current record's "type" value
 * @method StoreType           setStore() Sets the current record's "Store" collection
 * 
 * @package    collections
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStoreType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('store_type');
        $this->hasColumn('type', 'string', 1000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 1000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Stores as Store', array(
             'refClass' => 'StoreStoreType',
             'local' => 'store_type_id',
             'foreign' => 'stores_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}