<?php

/**
 * BaseStoreStoreType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $stores_id
 * @property integer $store_type_id
 * 
 * @method integer        getStoresId()      Returns the current record's "stores_id" value
 * @method integer        getStoreTypeId()   Returns the current record's "store_type_id" value
 * @method StoreStoreType setStoresId()      Sets the current record's "stores_id" value
 * @method StoreStoreType setStoreTypeId()   Sets the current record's "store_type_id" value
 * 
 * @package    collections
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStoreStoreType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('store_store_type');
        $this->hasColumn('stores_id', 'integer', 19, array(
             'type' => 'integer',
             'notnull' => false,
             'primary' => true,
             'length' => 19,
             ));
        $this->hasColumn('store_type_id', 'integer', 20, array(
             'type' => 'integer',
             'notnull' => false,
             'primary' => true,
             'length' => 20,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}