<?php

/**
 * BaseStoreNews
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $store_id
 * @property string $title
 * @property string $paragraph
 * @property Stores $Store
 * 
 * @method integer   getStoreId()   Returns the current record's "store_id" value
 * @method string    getTitle()     Returns the current record's "title" value
 * @method string    getParagraph() Returns the current record's "paragraph" value
 * @method Stores    getStore()     Returns the current record's "Store" value
 * @method StoreNews setStoreId()   Sets the current record's "store_id" value
 * @method StoreNews setTitle()     Sets the current record's "title" value
 * @method StoreNews setParagraph() Sets the current record's "paragraph" value
 * @method StoreNews setStore()     Sets the current record's "Store" value
 * 
 * @package    collections
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStoreNews extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('store_news');
        $this->hasColumn('store_id', 'integer', 19, array(
             'type' => 'integer',
             'length' => 19,
             ));
        $this->hasColumn('title', 'string', 1000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 1000,
             ));
        $this->hasColumn('paragraph', 'string', 4000, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 4000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Stores as Store', array(
             'local' => 'store_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}