<?php

/**
 * BaseSlExtraData
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $datakey
 * @property string $value
 * @property integer $store_id
 * @property SlStore $SlStore
 * 
 * @method string      getDatakey()  Returns the current record's "datakey" value
 * @method string      getValue()    Returns the current record's "value" value
 * @method integer     getStoreId()  Returns the current record's "store_id" value
 * @method SlStore     getSlStore()  Returns the current record's "SlStore" value
 * @method SlExtraData setDatakey()  Sets the current record's "datakey" value
 * @method SlExtraData setValue()    Sets the current record's "value" value
 * @method SlExtraData setStoreId()  Sets the current record's "store_id" value
 * @method SlExtraData setSlStore()  Sets the current record's "SlStore" value
 * 
 * @package    collections
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSlExtraData extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sl_extra_data');
        $this->hasColumn('datakey', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('value', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('store_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SlStore', array(
             'local' => 'store_id',
             'foreign' => 'id'));
    }
}