<?php

/**
 * BaseSlProductLine
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $ord
 * @property boolean $visible
 * @property Doctrine_Collection $SlStore
 * 
 * @method string              getName()    Returns the current record's "name" value
 * @method integer             getOrd()     Returns the current record's "ord" value
 * @method boolean             getVisible() Returns the current record's "visible" value
 * @method Doctrine_Collection getSlStore() Returns the current record's "SlStore" collection
 * @method SlProductLine       setName()    Sets the current record's "name" value
 * @method SlProductLine       setOrd()     Sets the current record's "ord" value
 * @method SlProductLine       setVisible() Sets the current record's "visible" value
 * @method SlProductLine       setSlStore() Sets the current record's "SlStore" collection
 * 
 * @package    collections
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSlProductLine extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sl_product_line');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('ord', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('visible', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('SlStore', array(
             'refClass' => 'SlStoreProductLine',
             'local' => 'sl_product_line_id',
             'foreign' => 'sl_store_id',
             'onDelete' => 'CASCADE'));
    }
}