<?php

/**
 * BaseSlWorldArea
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $SlStore
 * @property Doctrine_Collection $SlCountry
 * 
 * @method string              getName()      Returns the current record's "name" value
 * @method Doctrine_Collection getSlStore()   Returns the current record's "SlStore" collection
 * @method Doctrine_Collection getSlCountry() Returns the current record's "SlCountry" collection
 * @method SlWorldArea         setName()      Sets the current record's "name" value
 * @method SlWorldArea         setSlStore()   Sets the current record's "SlStore" collection
 * @method SlWorldArea         setSlCountry() Sets the current record's "SlCountry" collection
 * 
 * @package    collections
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSlWorldArea extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sl_world_area');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('SlStore', array(
             'local' => 'id',
             'foreign' => 'world_area_id'));

        $this->hasMany('SlCountry', array(
             'local' => 'id',
             'foreign' => 'world_area_id'));
    }
}