<?php

/**
 * BaseSlCity
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $country_id
 * @property SlCountry $SlCountry
 * @property Doctrine_Collection $SlStore
 * 
 * @method string              getName()       Returns the current record's "name" value
 * @method integer             getCountryId()  Returns the current record's "country_id" value
 * @method SlCountry           getSlCountry()  Returns the current record's "SlCountry" value
 * @method Doctrine_Collection getSlStore()    Returns the current record's "SlStore" collection
 * @method SlCity              setName()       Sets the current record's "name" value
 * @method SlCity              setCountryId()  Sets the current record's "country_id" value
 * @method SlCity              setSlCountry()  Sets the current record's "SlCountry" value
 * @method SlCity              setSlStore()    Sets the current record's "SlStore" collection
 * 
 * @package    collections
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSlCity extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sl_city');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('country_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SlCountry', array(
             'local' => 'country_id',
             'foreign' => 'id'));

        $this->hasMany('SlStore', array(
             'local' => 'id',
             'foreign' => 'city_id'));
    }
}