<?php

/**
 * BaseSlStoreProductLine
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $sl_store_id
 * @property integer $sl_product_line_id
 * 
 * @method integer            getSlStoreId()          Returns the current record's "sl_store_id" value
 * @method integer            getSlProductLineId()    Returns the current record's "sl_product_line_id" value
 * @method SlStoreProductLine setSlStoreId()          Sets the current record's "sl_store_id" value
 * @method SlStoreProductLine setSlProductLineId()    Sets the current record's "sl_product_line_id" value
 * 
 * @package    collections
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSlStoreProductLine extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sl_store_product_line');
        $this->hasColumn('sl_store_id', 'integer', 19, array(
             'type' => 'integer',
             'notnull' => false,
             'primary' => true,
             'length' => 19,
             ));
        $this->hasColumn('sl_product_line_id', 'integer', 20, array(
             'type' => 'integer',
             'notnull' => false,
             'primary' => true,
             'length' => 20,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}