<?php

/**
 * BaseStoreExtraData
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $store_id
 * @property string $info
 * @property string $additional_address
 * @property boolean $twotimeaday
 * @property object $opening_times
 * @property string $times_notes
 * @property Stores $Store
 * 
 * @method integer        getStoreId()            Returns the current record's "store_id" value
 * @method string         getInfo()               Returns the current record's "info" value
 * @method string         getAdditionalAddress()  Returns the current record's "additional_address" value
 * @method boolean        getTwotimeaday()        Returns the current record's "twotimeaday" value
 * @method object         getOpeningTimes()       Returns the current record's "opening_times" value
 * @method string         getTimesNotes()         Returns the current record's "times_notes" value
 * @method Stores         getStore()              Returns the current record's "Store" value
 * @method StoreExtraData setStoreId()            Sets the current record's "store_id" value
 * @method StoreExtraData setInfo()               Sets the current record's "info" value
 * @method StoreExtraData setAdditionalAddress()  Sets the current record's "additional_address" value
 * @method StoreExtraData setTwotimeaday()        Sets the current record's "twotimeaday" value
 * @method StoreExtraData setOpeningTimes()       Sets the current record's "opening_times" value
 * @method StoreExtraData setTimesNotes()         Sets the current record's "times_notes" value
 * @method StoreExtraData setStore()              Sets the current record's "Store" value
 * 
 * @package    collections
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStoreExtraData extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('store_extra_data');
        $this->hasColumn('store_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('info', 'string', 2000, array(
             'type' => 'string',
             'length' => 2000,
             ));
        $this->hasColumn('additional_address', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('twotimeaday', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('opening_times', 'object', null, array(
             'type' => 'object',
             ));
        $this->hasColumn('times_notes', 'string', 2000, array(
             'type' => 'string',
             'length' => 2000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Stores as Store', array(
             'local' => 'store_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}