<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/11/13 10:10:31

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=storelocator',
  'username' => 'root',
  'password' => NULL,
  'attributes' => 
  array (
    'default_table_collate' => 'utf8_unicode_ci',
    'default_table_charset' => 'utf8',
  ),
  'name' => 'doctrine',
)),);
