<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/11/13 10:10:31
sfConfig::add(array(
  'app_sf_admin_dash_web_dir' => '/sfAdminDashPlugin',
  'app_sf_admin_dash_image_dir' => '/sfAdminDashPlugin/images/icons/',
  'app_sf_admin_dash_default_image' => 'config.png',
  'app_sf_admin_dash_resize_mode' => 'thumbnail',
  'app_sf_admin_dash_logout' => true,
  'app_sf_admin_dash_site' => 'Diesel Store Locator Admin',
  'app_sf_admin_dash_include_path' => true,
  'app_sf_admin_dash_include_jquery_no_conflict' => false,
  'app_sf_admin_dash_login_route' => '@sf_guard_signin',
  'app_sf_admin_dash_logout_route' => '@sf_guard_signout',
  'app_sf_admin_dash_categories' => array (
  'Users' => 
  array (
    'items' => 
    array (
      'Users' => 
      array (
        'url' => 'sf_guard_user',
      ),
      'Groups' => 
      array (
        'url' => 'sf_guard_group',
      ),
      'Permissions' => 
      array (
        'url' => 'sf_guard_permission',
      ),
    ),
  ),
  'Stores' => 
  array (
    'items' => 
    array (
      'Stores' => 
      array (
        'url' => 'sl_store',
      ),
      'News' => 
      array (
        'url' => 'sl_store_news',
      ),
    ),
  ),
  'Localization' => 
  array (
    'items' => 
    array (
      'World Areas' => 
      array (
        'url' => 'sl_world_area',
      ),
      'Countries' => 
      array (
        'url' => 'sl_country',
      ),
      'Cities' => 
      array (
        'url' => 'sl_city',
      ),
    ),
  ),
  'Store Datas' => 
  array (
    'items' => 
    array (
      'Store Types' => 
      array (
        'url' => 'sl_store_type',
      ),
      'Store Statuses' => 
      array (
        'url' => 'sl_store_status',
      ),
      'Product Line' => 
      array (
        'url' => 'sl_product_line',
      ),
    ),
  ),
),
));
