<?php

/**
 * SlCityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SlCityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SlCityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SlCity');
    }
}