<?php

/**
 * SlCountryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SlCountryTable extends Doctrine_Table {
  
    /**
     * Returns an instance of this class.
     *
     * @return object SlCountryTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('SlCountry');
    }//getInstance
    
    public function getCountries($addempty) {
      $contries = parent::createQuery('SlCountryTable s')
          ->distinct()
          ->orderBy('s.name')
          ->execute();
      
      $res = array();
      if( $addempty === true ){
    	$res[""] = "All Country";
      }//if
    
      foreach ($contries as $country) {
        $res[$country->getId()] = $country->getName();
      }//foreach
      
      //var_dump($res);
      
      return $res;
    }//getCountries
    
}//SlCountryTable