<?php

/**
 * SlExtraData
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    collections
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SlExtraData extends BaseSlExtraData {

  const TIMESTABLE = 'TIMESTABLE';
  const INFO = 'INFO';
  const ADDITIONAL_ADDRESS = 'ADDITIONAL_ADDRESS';
  const TWO_TIMES_A_DAY = 'TWO_TIMES_A_DAY';
  const HAS_TIMESTABLE = 'HAS_TIMESTABLE';

}//SlExtraData
