<?php

/**
 * SlExtraDataTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SlExtraDataTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SlExtraDataTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SlExtraData');
    }
}