<?php

/**
 * SlStoreStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SlStoreStatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SlStoreStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SlStoreStatus');
    }
}