<?php

/**
 * SlStoreProductLineTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SlStoreProductLineTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SlStoreProductLineTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SlStoreProductLine');
    }
}