<?php

/**
 * SlStoreNewsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SlStoreNewsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SlStoreNewsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SlStoreNews');
    }
}