<?php

/**
 * SlStoreStoreTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SlStoreStoreTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SlStoreStoreTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SlStoreStoreType');
    }
}