<?php

/**
 * SlStoreTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SlStoreTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SlStoreTypeTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('SlStoreType');
    }
    
    public function getStoreTypesArray(){
      $types = $this->findAll();
      $res = array('' => 'All');
      foreach ($types as $t) {
        $res[$t->getId()] = $t->getName();
      }//foreach
      return $res;
    }//getStoreTypesArray

}