<?php

/**
 * SlWorldAreaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SlWorldAreaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SlWorldAreaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SlWorldArea');
    }
}