<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('store_news', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'store_id' => 
             array(
              'type' => 'integer',
              'length' => '19',
             ),
             'title' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '1000',
             ),
             'paragraph' => 
             array(
              'type' => 'string',
              'notnull' => '',
              'length' => '4000',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->addColumn('store_extra_data', 'additional_address', 'string', '255', array(
             ));
        $this->addColumn('store_extra_data', 'twotimeaday', 'boolean', '25', array(
             ));
        $this->addColumn('store_extra_data', 'opening_times', 'object', '', array(
             ));
        $this->addColumn('store_extra_data', 'times_notes', 'string', '2000', array(
             ));
        $this->addColumn('stores', 'user_id', 'integer', '11', array(
             ));
        $this->changeColumn('stores', 'id', 'integer', '19', array(
             ));
    }

    public function down()
    {
        $this->dropTable('store_news');
        $this->removeColumn('store_extra_data', 'additional_address');
        $this->removeColumn('store_extra_data', 'twotimeaday');
        $this->removeColumn('store_extra_data', 'opening_times');
        $this->removeColumn('store_extra_data', 'times_notes');
        $this->removeColumn('stores', 'user_id');
    }
}