<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $conn = Doctrine_Manager::getInstance()->getCurrentConnection();

       // $conn->exec('ALTER TABLE stores ENGINE=INNODB');
      
        $this->createForeignKey('store_news', 'store_news_store_id_stores_id', array(
             'name' => 'store_news_store_id_stores_id',
             'local' => 'store_id',
             'foreign' => 'id',
             'foreignTable' => 'stores',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('store_news', 'store_news_store_id', array(
             'fields' => 
             array(
              0 => 'store_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('store_news', 'store_news_store_id_stores_id');
        $this->removeIndex('store_news', 'store_news_store_id', array(
             'fields' => 
             array(
              0 => 'store_id',
             ),
             ));
        $conn = Doctrine_Manager::getInstance()->getCurrentConnection();

      //  $conn->exec('ALTER TABLE stores ENGINE=MyISAM');
    }
}