<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('store_store_type', array(
             'stores_id' => 
             array(
              'type' => 'integer',
              'notnull' => '',
              'primary' => '1',
              'length' => '19',
             ),
             'store_type_id' => 
             array(
              'type' => 'integer',
              'notnull' => '',
              'primary' => '1',
              'length' => '20',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'stores_id',
              1 => 'store_type_id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('store_type', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'type' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '1000',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('store_store_type');
        $this->dropTable('store_type');
    }
}