<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addslstorenews extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('sl_store_news', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'store_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'title' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 1000,
             ),
             'paragraph' => 
             array(
              'type' => 'string',
              'notnull' => false,
              'length' => 4000,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'slug' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             ), array(
             'indexes' => 
             array(
              'sl_store_news_sluggable' => 
              array(
              'fields' => 
              array(
               0 => 'slug',
              ),
              'type' => 'unique',
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('sl_store_news');
    }
}