<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addfks extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('sl_city', 'sl_city_country_id_sl_country_id', array(
             'name' => 'sl_city_country_id_sl_country_id',
             'local' => 'country_id',
             'foreign' => 'id',
             'foreignTable' => 'sl_country',
             ));
        $this->createForeignKey('sl_country', 'sl_country_world_area_id_sl_world_area_id', array(
             'name' => 'sl_country_world_area_id_sl_world_area_id',
             'local' => 'world_area_id',
             'foreign' => 'id',
             'foreignTable' => 'sl_world_area',
             ));
        $this->createForeignKey('sl_extra_data', 'sl_extra_data_store_id_sl_store_id', array(
             'name' => 'sl_extra_data_store_id_sl_store_id',
             'local' => 'store_id',
             'foreign' => 'id',
             'foreignTable' => 'sl_store',
             ));
        $this->createForeignKey('sl_store', 'sl_store_world_area_id_sl_world_area_id', array(
             'name' => 'sl_store_world_area_id_sl_world_area_id',
             'local' => 'world_area_id',
             'foreign' => 'id',
             'foreignTable' => 'sl_world_area',
             ));
        $this->createForeignKey('sl_store', 'sl_store_country_id_sl_country_id', array(
             'name' => 'sl_store_country_id_sl_country_id',
             'local' => 'country_id',
             'foreign' => 'id',
             'foreignTable' => 'sl_country',
             ));
        $this->createForeignKey('sl_store', 'sl_store_city_id_sl_city_id', array(
             'name' => 'sl_store_city_id_sl_city_id',
             'local' => 'city_id',
             'foreign' => 'id',
             'foreignTable' => 'sl_city',
             ));
        $this->createForeignKey('sl_store', 'sl_store_store_type_id_sl_store_type_id', array(
             'name' => 'sl_store_store_type_id_sl_store_type_id',
             'local' => 'store_type_id',
             'foreign' => 'id',
             'foreignTable' => 'sl_store_type',
             ));
        $this->createForeignKey('sl_store', 'sl_store_store_status_id_sl_store_status_id', array(
             'name' => 'sl_store_store_status_id_sl_store_status_id',
             'local' => 'store_status_id',
             'foreign' => 'id',
             'foreignTable' => 'sl_store_status',
             ));
        $this->createForeignKey('sl_store', 'sl_store_product_line_id_sl_product_line_id', array(
             'name' => 'sl_store_product_line_id_sl_product_line_id',
             'local' => 'product_line_id',
             'foreign' => 'id',
             'foreignTable' => 'sl_product_line',
             ));
        $this->createForeignKey('sl_store_news', 'sl_store_news_store_id_sl_store_id', array(
             'name' => 'sl_store_news_store_id_sl_store_id',
             'local' => 'store_id',
             'foreign' => 'id',
             'foreignTable' => 'sl_store',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sl_store_store_type', 'sl_store_store_type_sl_store_id_sl_store_id', array(
             'name' => 'sl_store_store_type_sl_store_id_sl_store_id',
             'local' => 'sl_store_id',
             'foreign' => 'id',
             'foreignTable' => 'sl_store',
             ));
    }

    public function down()
    {
        $this->dropForeignKey('sl_city', 'sl_city_country_id_sl_country_id');
        $this->dropForeignKey('sl_country', 'sl_country_world_area_id_sl_world_area_id');
        $this->dropForeignKey('sl_extra_data', 'sl_extra_data_store_id_sl_store_id');
        $this->dropForeignKey('sl_store', 'sl_store_world_area_id_sl_world_area_id');
        $this->dropForeignKey('sl_store', 'sl_store_country_id_sl_country_id');
        $this->dropForeignKey('sl_store', 'sl_store_city_id_sl_city_id');
        $this->dropForeignKey('sl_store', 'sl_store_store_type_id_sl_store_type_id');
        $this->dropForeignKey('sl_store', 'sl_store_store_status_id_sl_store_status_id');
        $this->dropForeignKey('sl_store', 'sl_store_product_line_id_sl_product_line_id');
        $this->dropForeignKey('sl_store_news', 'sl_store_news_store_id_sl_store_id');
        $this->dropForeignKey('sl_store_store_type', 'sl_store_store_type_sl_store_id_sl_store_id');
    }
}