<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version17 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('sl_country', 'user_id', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('sl_country', 'user_id');
    }
}