<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addslstore extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('sl_store', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'address' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'zip' => 
             array(
              'type' => 'string',
              'length' => 20,
             ),
             'telf' => 
             array(
              'type' => 'string',
              'length' => 20,
             ),
             'latitude' => 
             array(
              'type' => 'string',
              'default' => '0',
              'length' => 10,
             ),
             'longitude' => 
             array(
              'type' => 'string',
              'default' => '0',
              'length' => 10,
             ),
             'position' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'world_area_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'country_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'city_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'store_type_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'store_status_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'product_line_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'slug' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             ), array(
             'indexes' => 
             array(
              'name_idx' => 
              array(
              'fields' => 
              array(
               0 => 'name',
              ),
              ),
              'city_idx' => 
              array(
              'fields' => 
              array(
               0 => 'city_id',
              ),
              ),
              'country_idx' => 
              array(
              'fields' => 
              array(
               0 => 'country_id',
              ),
              ),
              'store_type_idx' => 
              array(
              'fields' => 
              array(
               0 => 'store_type_id',
              ),
              ),
              'store_status_idx' => 
              array(
              'fields' => 
              array(
               0 => 'store_status_id',
              ),
              ),
              'sl_store_sluggable' => 
              array(
              'fields' => 
              array(
               0 => 'slug',
              ),
              'type' => 'unique',
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('sl_store');
    }
}