<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addslstorestoretype extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('sl_store_store_type', array(
             'sl_store_id' => 
             array(
              'type' => 'integer',
              'notnull' => false,
              'primary' => true,
              'length' => 19,
             ),
             'sl_store_type_id' => 
             array(
              'type' => 'integer',
              'notnull' => false,
              'primary' => true,
              'length' => 20,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'sl_store_id',
              1 => 'sl_store_type_id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('sl_store_store_type');
    }
}