<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version19 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('sl_store_product_line', array(
             'sl_store_id' => 
             array(
              'type' => 'integer',
              'notnull' => '',
              'primary' => '1',
              'length' => '19',
             ),
             'sl_product_line_id' => 
             array(
              'type' => 'integer',
              'notnull' => '',
              'primary' => '1',
              'length' => '20',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'sl_store_id',
              1 => 'sl_product_line_id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('sl_store_product_line');
    }
}