<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version20 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('sl_store', 'sl_store_product_line_id_sl_product_line_id');
        $this->createForeignKey('sl_store_product_line', 'sl_store_product_line_sl_product_line_id_sl_product_line_id', array(
             'name' => 'sl_store_product_line_sl_product_line_id_sl_product_line_id',
             'local' => 'sl_product_line_id',
             'foreign' => 'id',
             'foreignTable' => 'sl_product_line',
             ));
        $this->createForeignKey('sl_store_product_line', 'sl_store_product_line_sl_store_id_sl_store_id', array(
             'name' => 'sl_store_product_line_sl_store_id_sl_store_id',
             'local' => 'sl_store_id',
             'foreign' => 'id',
             'foreignTable' => 'sl_store',
             ));
        $this->addIndex('sl_store_product_line', 'sl_store_product_line_sl_product_line_id', array(
             'fields' => 
             array(
              0 => 'sl_product_line_id',
             ),
             ));
        $this->addIndex('sl_store_product_line', 'sl_store_product_line_sl_store_id', array(
             'fields' => 
             array(
              0 => 'sl_store_id',
             ),
             ));
    }

    public function down()
    {
        $this->createForeignKey('sl_store', 'sl_store_product_line_id_sl_product_line_id', array(
             'name' => 'sl_store_product_line_id_sl_product_line_id',
             'local' => 'product_line_id',
             'foreign' => 'id',
             'foreignTable' => 'sl_product_line',
             ));
        $this->dropForeignKey('sl_store_product_line', 'sl_store_product_line_sl_product_line_id_sl_product_line_id');
        $this->dropForeignKey('sl_store_product_line', 'sl_store_product_line_sl_store_id_sl_store_id');
        $this->removeIndex('sl_store_product_line', 'sl_store_product_line_sl_product_line_id', array(
             'fields' => 
             array(
              0 => 'sl_product_line_id',
             ),
             ));
        $this->removeIndex('sl_store_product_line', 'sl_store_product_line_sl_store_id', array(
             'fields' => 
             array(
              0 => 'sl_store_id',
             ),
             ));
    }
}