<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version21 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('sl_store', 'online', 'integer', '8', array(
             'default' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('sl_store', 'online');
    }
}