<?php

/**
 * sfGuardUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    collections
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardUser extends PluginsfGuardUser {
  
  public function getCountriesArray() {
    $countries = $this->getCountries();
    $arCountries = array();
    foreach ($countries as $c) {
      $arCountries[] = $c->getId();
    }// foreach
    return $arCountries;
  }//getCountriesArray
  
  
  public function getUserStores() {
    
  }//getUserStores
  
}//sfGuardUser